gatling {
  core {
    extract {
      regex {
        cacheMaxCapacity = 200
      }
    }
  }

  charting {
    indicators {
      lowerBound = 800    # ms
      higherBound = 1200  # ms
    }
  }
}

